baseURL = "https://blog.rwhitedwarf.com"
title = "R with White Dwarf"
author = "White Dwarf"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Enable for syntax highlighting
pygmentsUseClasses = false
pygmentsCodefences = true

      
# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-4BW3ZE1JE8"

# Disqus Comment System
#disqusShortname = ""

# RSS
copyright = '2021 R White Dwarf all rights reserved'

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-blue-900"#"bg-gray-800"

#Site description
description = "R tutorials and guides."

# The number of articles to be displayed on a single page.
paginator_pages = "10"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "light"

css = ["css/custom.css"]

  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = true

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "w-auto"

    # Number of characters in description
    description = "130"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "tags", "recent", "external_sources", "archive", "category"]

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      #[markup.goldmark.parser.attribute]
      #  block = false
      #  title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
    [markup.highlight]
      style = 'emacs'
      cssstyles = 'emacs'
      prestyles = 'emacs'
      codeFences = true
      guessSyntax = true
      ineNoStart = 1
      lineNos = false
      #linenos = 'table'
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = true
      wrapcode = true